/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hy_testjni_MyJni */

#ifndef _Included_com_hy_testjni_MyJni
#define _Included_com_hy_testjni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hy_testjni_MyJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hy_testjni_MyJni_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
